### PR TITLE
Support new FTP structure + output directory

### PR DESCRIPTION
**Pull request by muffato**
https://jira.sanger.ac.uk/browse/TOLIT-954

Ensembl have now introduced an extra directory level on their FTP to indicate the annotation method: https://www.ensembl.info/2022/11/08/updates-to-the-ensembl-rapid-release-ftp-site/

This pipeline too needs to be aware of the _gene_ annotation method, even if the _repeat_ annotation is the same regardless of the gene annotation method. That's a requirement of the FTP directory structure.
This PR simply adds the extra parameter, and as in https://github.com/sanger-tol/ensemblgenedownload/pull/2 changes the way relative output paths from the sample-sheet are interpreted 

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/ensemblrepeatdownload/tree/master/.github/CONTRIBUTING.md)
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
`nf-core lint` on GitHub was confused by the structure of the repository because it ran the latest nf-core whereas this pipeline is based on nf-core 2.5. By pinning the version used in the CI (d74ec900b78f1895927cc0b83540843ac5310e60), `nf-core lint` now passes

**Comment by muffato** [comment]
All tests pass now ! Sorry, I realised I had only checked the `test_full` profile locally, not `test`

**Review by priyanka-surana — APPROVED** [review]
LGTM 👍 

Seemed similar to the other Ensembl download pipeline. Same suggestions too.

**Comment by muffato** [comment]
I've renamed most of the "it"

**Pull request merged**
